### PR TITLE
Updated PHPUnit to 5.7 which is still compatible with PHP 5.6 but is also compatible with PHP 7.2

### PR DESCRIPTION
**Pull request by morozov**
This should fix the [build failure](https://travis-ci.org/kix/mdash/jobs/396792246). Additionally, `config.platform.php` is locked in `composer.json` in order to prevent incompatible dependencies from being installed.

### CODE REVIEW

**Comment by morozov** [comment]
@kix once the build is stabilized, do you mind tagging a release?

**Comment by kix** [comment]
@morozov, tagged `0.5.5`

**Comment by morozov** [comment]
Thank you, @kix!

**Comment by kix** [comment]
@morozov, thanks for contributing the fix :)

**Pull request merged**
